Reverting, so I don't cause further bustage.  a=burning Jenkins on v1-train
For reference/context:

Searching for marionette-client>=0.5.37
Reading http://pypi.python.org/simple/marionette_client/
No local packages or download links found for marionette-client>=0.5.37
error: Could not find suitable distribution for Requirement.parse('marionette-client>=0.5.37')